// <auto-generated>
using System.Runtime.CompilerServices;

namespace DemoFile;

internal static class FieldPathEncoding
{
    public static bool ReadFieldPathOp(ref BitBuffer buffer, ref FieldPath path)
    {
        if (!buffer.ReadOneBit())
        {
            // Frequency: 36271
            // Bit string: 0
            PlusOne(ref buffer, ref path);
            return true;
        }
        else
        {
            if (!buffer.ReadOneBit())
            {
                // Frequency: 25474
                // Bit string: 10
                return false;
            }
            else
            {
                if (!buffer.ReadOneBit())
                {
                    if (!buffer.ReadOneBit())
                    {
                        if (!buffer.ReadOneBit())
                        {
                            // Frequency: 2942
                            // Bit string: 11000
                            PushOneLeftDeltaOneRightNonZero(ref buffer, ref path);
                            return true;
                        }
                        else
                        {
                            if (!buffer.ReadOneBit())
                            {
                                // Frequency: 1375
                                // Bit string: 110010
                                PlusThree(ref buffer, ref path);
                                return true;
                            }
                            else
                            {
                                // Frequency: 1837
                                // Bit string: 110011
                                PopAllButOnePlusOne(ref buffer, ref path);
                                return true;
                            }
                        }
                    }
                    else
                    {
                        if (!buffer.ReadOneBit())
                        {
                            // Frequency: 4128
                            // Bit string: 11010
                            PlusN(ref buffer, ref path);
                            return true;
                        }
                        else
                        {
                            if (!buffer.ReadOneBit())
                            {
                                if (!buffer.ReadOneBit())
                                {
                                    if (!buffer.ReadOneBit())
                                    {
                                        if (!buffer.ReadOneBit())
                                        {
                                            // Frequency: 149
                                            // Bit string: 110110000
                                            PopAllButOnePlusN(ref buffer, ref path);
                                            return true;
                                        }
                                        else
                                        {
                                            if (!buffer.ReadOneBit())
                                            {
                                                // Frequency: 99
                                                // Bit string: 1101100010
                                                NonTopoComplexPack4Bits(ref buffer, ref path);
                                                return true;
                                            }
                                            else
                                            {
                                                if (!buffer.ReadOneBit())
                                                {
                                                    if (!buffer.ReadOneBit())
                                                    {
                                                        if (!buffer.ReadOneBit())
                                                        {
                                                            if (!buffer.ReadOneBit())
                                                            {
                                                                if (!buffer.ReadOneBit())
                                                                {
                                                                    if (!buffer.ReadOneBit())
                                                                    {
                                                                        // Frequency: 1
                                                                        // Bit string: 1101100011000000
                                                                        PopNAndNonTopographical(ref buffer, ref path);
                                                                        return true;
                                                                    }
                                                                    else
                                                                    {
                                                                        // Frequency: 0
                                                                        // Bit string: 1101100011000001
                                                                        PopNPlusN(ref buffer, ref path);
                                                                        return true;
                                                                    }
                                                                }
                                                                else
                                                                {
                                                                    // Frequency: 2
                                                                    // Bit string: 110110001100001
                                                                    PopOnePlusOne(ref buffer, ref path);
                                                                    return true;
                                                                }
                                                            }
                                                            else
                                                            {
                                                                if (!buffer.ReadOneBit())
                                                                {
                                                                    if (!buffer.ReadOneBit())
                                                                    {
                                                                        // Frequency: 0
                                                                        // Bit string: 1101100011000100
                                                                        PushN(ref buffer, ref path);
                                                                        return true;
                                                                    }
                                                                    else
                                                                    {
                                                                        // Frequency: 0
                                                                        // Bit string: 1101100011000101
                                                                        PushThreePack5LeftDeltaN(ref buffer, ref path);
                                                                        return true;
                                                                    }
                                                                }
                                                                else
                                                                {
                                                                    if (!buffer.ReadOneBit())
                                                                    {
                                                                        // Frequency: 0
                                                                        // Bit string: 1101100011000110
                                                                        PopNPlusOne(ref buffer, ref path);
                                                                        return true;
                                                                    }
                                                                    else
                                                                    {
                                                                        // Frequency: 0
                                                                        // Bit string: 1101100011000111
                                                                        PopOnePlusN(ref buffer, ref path);
                                                                        return true;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                        else
                                                        {
                                                            if (!buffer.ReadOneBit())
                                                            {
                                                                if (!buffer.ReadOneBit())
                                                                {
                                                                    if (!buffer.ReadOneBit())
                                                                    {
                                                                        // Frequency: 0
                                                                        // Bit string: 1101100011001000
                                                                        PushTwoLeftDeltaZero(ref buffer, ref path);
                                                                        return true;
                                                                    }
                                                                    else
                                                                    {
                                                                        if (!buffer.ReadOneBit())
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110010010
                                                                            PushThreeLeftDeltaZero(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                        else
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110010011
                                                                            PushTwoPack5LeftDeltaZero(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                    }
                                                                }
                                                                else
                                                                {
                                                                    // Frequency: 3
                                                                    // Bit string: 110110001100101
                                                                    PushOneLeftDeltaZeroRightNonZero(ref buffer, ref path);
                                                                    return true;
                                                                }
                                                            }
                                                            else
                                                            {
                                                                if (!buffer.ReadOneBit())
                                                                {
                                                                    if (!buffer.ReadOneBit())
                                                                    {
                                                                        if (!buffer.ReadOneBit())
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011000
                                                                            PushTwoLeftDeltaN(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                        else
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011001
                                                                            PushThreePack5LeftDeltaOne(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                    }
                                                                    else
                                                                    {
                                                                        if (!buffer.ReadOneBit())
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011010
                                                                            PushThreeLeftDeltaN(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                        else
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011011
                                                                            PushTwoPack5LeftDeltaN(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                    }
                                                                }
                                                                else
                                                                {
                                                                    if (!buffer.ReadOneBit())
                                                                    {
                                                                        if (!buffer.ReadOneBit())
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011100
                                                                            PushTwoLeftDeltaOne(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                        else
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011101
                                                                            PushThreePack5LeftDeltaZero(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                    }
                                                                    else
                                                                    {
                                                                        if (!buffer.ReadOneBit())
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011110
                                                                            PushThreeLeftDeltaOne(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                        else
                                                                        {
                                                                            // Frequency: 0
                                                                            // Bit string: 11011000110011111
                                                                            PushTwoPack5LeftDeltaOne(ref buffer, ref path);
                                                                            return true;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                    else
                                                    {
                                                        // Frequency: 35
                                                        // Bit string: 110110001101
                                                        PushOneLeftDeltaZeroRightZero(ref buffer, ref path);
                                                        return true;
                                                    }
                                                }
                                                else
                                                {
                                                    // Frequency: 76
                                                    // Bit string: 11011000111
                                                    NonTopoComplex(ref buffer, ref path);
                                                    return true;
                                                }
                                            }
                                        }
                                    }
                                    else
                                    {
                                        // Frequency: 471
                                        // Bit string: 11011001
                                        PushOneLeftDeltaNRightNonZero(ref buffer, ref path);
                                        return true;
                                    }
                                }
                                else
                                {
                                    if (!buffer.ReadOneBit())
                                    {
                                        // Frequency: 521
                                        // Bit string: 11011010
                                        PushOneLeftDeltaOneRightZero(ref buffer, ref path);
                                        return true;
                                    }
                                    else
                                    {
                                        if (!buffer.ReadOneBit())
                                        {
                                            // Frequency: 251
                                            // Bit string: 110110110
                                            PushOneLeftDeltaNRightNonZeroPack8Bits(ref buffer, ref path);
                                            return true;
                                        }
                                        else
                                        {
                                            // Frequency: 271
                                            // Bit string: 110110111
                                            NonTopoPenultimatePlusOne(ref buffer, ref path);
                                            return true;
                                        }
                                    }
                                }
                            }
                            else
                            {
                                if (!buffer.ReadOneBit())
                                {
                                    if (!buffer.ReadOneBit())
                                    {
                                        // Frequency: 560
                                        // Bit string: 11011100
                                        PushOneLeftDeltaNRightZero(ref buffer, ref path);
                                        return true;
                                    }
                                    else
                                    {
                                        if (!buffer.ReadOneBit())
                                        {
                                            // Frequency: 300
                                            // Bit string: 110111010
                                            PopAllButOnePlusNPack3Bits(ref buffer, ref path);
                                            return true;
                                        }
                                        else
                                        {
                                            // Frequency: 310
                                            // Bit string: 110111011
                                            PushNAndNonTopological(ref buffer, ref path);
                                            return true;
                                        }
                                    }
                                }
                                else
                                {
                                    if (!buffer.ReadOneBit())
                                    {
                                        // Frequency: 634
                                        // Bit string: 11011110
                                        PopAllButOnePlusNPack6Bits(ref buffer, ref path);
                                        return true;
                                    }
                                    else
                                    {
                                        // Frequency: 646
                                        // Bit string: 11011111
                                        PlusFour(ref buffer, ref path);
                                        return true;
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    if (!buffer.ReadOneBit())
                    {
                        // Frequency: 10334
                        // Bit string: 1110
                        PlusTwo(ref buffer, ref path);
                        return true;
                    }
                    else
                    {
                        // Frequency: 10530
                        // Bit string: 1111
                        PushOneLeftDeltaNRightNonZeroPack6Bits(ref buffer, ref path);
                        return true;
                    }
                }
            }
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PlusOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaOneRightNonZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 1;
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PlusThree(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 3;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopAllButOnePlusOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(path.Count - 1);
        path[0] += 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PlusN(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += buffer.ReadUBitVarFieldPath() + 5;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopAllButOnePlusN(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(path.Count - 1);
        path[0] += buffer.ReadUBitVarFieldPath() + 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void NonTopoComplexPack4Bits(ref BitBuffer buffer, ref FieldPath path)
    {
        for (var i = 0; i < path.Count; ++i)
        {
            if (buffer.ReadOneBit())
            {
                path[i] += (int) buffer.ReadUBits(4) - 7;
            }
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopNAndNonTopographical(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(buffer.ReadUBitVarFieldPath());
        for (var i = 0; i < path.Count; ++i)
        {
            if (buffer.ReadOneBit())
            {
                path[i] += buffer.ReadVarInt32();
            }
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopNPlusN(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(buffer.ReadUBitVarFieldPath());
        path[^1] += buffer.ReadVarInt32();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopOnePlusOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(1);
        path[^1] += 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushN(ref BitBuffer buffer, ref FieldPath path)
    {
        var count = (int) buffer.ReadUBitVar();
        path[^1] += (int) buffer.ReadUBitVar();
        for (var i = 0; i < count; ++i)
        {
            path.Add(buffer.ReadUBitVarFieldPath());
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushThreePack5LeftDeltaN(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += (int) buffer.ReadUBitVar() + 2;
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopNPlusOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(buffer.ReadUBitVarFieldPath());
        path[^1] += 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopOnePlusN(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(1);
        path[^1] += buffer.ReadUBitVarFieldPath() + 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushTwoLeftDeltaZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushThreeLeftDeltaZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushTwoPack5LeftDeltaZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaZeroRightNonZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushTwoLeftDeltaN(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += (int) buffer.ReadUBitVar() + 2;
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushThreePack5LeftDeltaOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 1;
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushThreeLeftDeltaN(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += (int) buffer.ReadUBitVar() + 2;
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushTwoPack5LeftDeltaN(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += (int) buffer.ReadUBitVar() + 2;
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushTwoLeftDeltaOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 1;
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushThreePack5LeftDeltaZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushThreeLeftDeltaOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 1;
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
        path.Add(buffer.ReadUBitVarFieldPath());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushTwoPack5LeftDeltaOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 1;
        path.Add((int) buffer.ReadUBits(5));
        path.Add((int) buffer.ReadUBits(5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaZeroRightZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Add(0);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void NonTopoComplex(ref BitBuffer buffer, ref FieldPath path)
    {
        for (var i = 0; i < path.Count; ++i)
        {
            if (buffer.ReadOneBit())
            {
                path[i] += buffer.ReadVarInt32();
            }
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaNRightNonZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += buffer.ReadUBitVarFieldPath() + 2;
        path.Add(buffer.ReadUBitVarFieldPath() + 1);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaOneRightZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 1;
        path.Add(0);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaNRightNonZeroPack8Bits(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += (int) buffer.ReadUBits(4) + 2;
        path.Add((int) buffer.ReadUBits(4) + 1);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void NonTopoPenultimatePlusOne(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^2] += 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaNRightZero(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += buffer.ReadUBitVarFieldPath();
        path.Add(0);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopAllButOnePlusNPack3Bits(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(path.Count - 1);
        path[0] += (int) buffer.ReadUBits(3) + 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushNAndNonTopological(ref BitBuffer buffer, ref FieldPath path)
    {
        for (var i = 0; i < path.Count; ++i)
        {
            if (buffer.ReadOneBit())
            {
                path[i] += buffer.ReadVarInt32() + 1;
            }
        }
        
        var count = (int) buffer.ReadUBitVar();
        for (var i = 0; i < count; ++i)
        {
            path.Add(buffer.ReadUBitVarFieldPath());
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PopAllButOnePlusNPack6Bits(ref BitBuffer buffer, ref FieldPath path)
    {
        path.Pop(path.Count - 1);
        path[0] += (int) buffer.ReadUBits(6) + 1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PlusFour(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 4;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PlusTwo(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += 2;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void PushOneLeftDeltaNRightNonZeroPack6Bits(ref BitBuffer buffer, ref FieldPath path)
    {
        path[^1] += (int) buffer.ReadUBits(3) + 2;
        path.Add((int) buffer.ReadUBits(3) + 1);
    }
}
